---

- name: Render configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart open-xchange
  loop:
    - opt/open-xchange/etc/client-onboarding.properties
    - opt/open-xchange/etc/client-onboarding-caldav.properties
    - opt/open-xchange/etc/client-onboarding-carddav.properties
    - opt/open-xchange/etc/client-onboarding-driveapp.properties
    - opt/open-xchange/etc/client-onboarding-eas.properties
    - opt/open-xchange/etc/client-onboarding-mail.properties
    - opt/open-xchange/etc/client-onboarding-mailapp.properties
    - opt/open-xchange/etc/client-onboarding-emclient.properties
    - opt/open-xchange/etc/client-onboarding-syncapp.properties
    - opt/open-xchange/etc/client-onboarding-scenarios.yml
    - opt/open-xchange/etc/client-onboarding-maillogin.properties
