---

- name: Enable Apache2 modules
  community.general.apache2_module:
    name: "{{ item }}"
  loop: "{{ apache2_ox_modules + apache2_additional_modules }}"
  notify: restart apache2

- name: Render Apache2 vhost
  ansible.builtin.template:
    src: etc/apache2/sites-available/oxappsuite.conf.j2
    dest: /etc/apache2/sites-available/oxappsuite.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload apache2

- name: Enable Apache2 vhost
  ansible.builtin.file:
    path: /etc/apache2/sites-enabled/oxappsuite.conf
    src: /etc/apache2/sites-available/oxappsuite.conf
    state: link
    owner: root
    group: root
    mode: "0644"
  notify: reload apache2
