---

- name: Render properties files
  ansible.builtin.template:
    src: "opt/open-xchange/mobile-api-facade/etc/{{ item }}.j2"
    dest: "/opt/open-xchange/mobile-api-facade/etc/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart open-xchange-mobile-api-facade
  loop:
    - facade.properties
    - mobile-api-facade-config.yml

- name: Start and enable the Mobile API Facade server
  ansible.builtin.service:
    name: open-xchange-mobile-api-facade
    state: started
    enabled: true
