---

- name: Load versions-specific vars
  ansible.builtin.include_vars: "ox_{{ appsuite_version }}.yml"

- name: Add apt repositories for Open-Xchange Mobile API Facade components
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  loop:
    - "{{ mobileapifacade_repository_facade }}"

- name: Install Mobile API Facade packages
  ansible.builtin.apt:
    name: "{{ mobileapifacade_package_list }}"
  notify:
    - Restart Open-Xchange
