---

appsuite_temurin_repository_release: "{{ ansible_facts.distribution_release }}"

appsuite_version: "7.10.6"

appsuite_repository_username: null
appsuite_repository_password: null
appsuite_repository_release: "Debian{{ ansible_facts.distribution_release[0] | upper }}{{ ansible_facts.distribution_release[1:] }}"

appsuite_repository_backend: >-
  deb https://software.open-xchange.com/products/appsuite/{{ appsuite_version }}/backend/{{ appsuite_repository_release }}/ /
appsuite_repository_appsuiteui: >-
  deb https://software.open-xchange.com/products/appsuite/{{ appsuite_version }}/appsuiteui/{{ appsuite_repository_release }}/ /

appsuite_repository_backend_updates: >-
  deb https://software.open-xchange.com/products/appsuite/{{ appsuite_version }}/backend/updates/{{ appsuite_repository_release }}/ /
appsuite_repository_appsuiteui_updates: >-
  deb https://software.open-xchange.com/products/appsuite/{{ appsuite_version }}/appsuiteui/updates/{{ appsuite_repository_release }}/ /
appsuite_repository_component_updates: false  # requires OX AppSuite 7 subscription

appsuite_authplugin: open-xchange-authentication-database
appsuite_python_mysql_library: python3-pymysql


appsuite_configdb_host: localhost
appsuite_configdb_port: 3306
appsuite_configdb_database: configdb
appsuite_configdb_user: openexchange
appsuite_configdb_root_user: root
appsuite_configdb_createuser: true

appsuite_configdb_write_host: "{{ appsuite_configdb_host }}"
appsuite_configdb_write_port: "{{ appsuite_configdb_port }}"
appsuite_configdb_write_database: "{{ appsuite_configdb_database }}"
appsuite_configdb_write_user: "{{ appsuite_configdb_user }}"
appsuite_configdb_write_pass: "{{ appsuite_configdb_pass }}"
appsuite_configdb_write_driver: "com.mysql.jdbc.Driver"
appsuite_configdb_write_url: "jdbc:mysql://{{ appsuite_configdb_write_host }}:{{ appsuite_configdb_write_port }}/{{ appsuite_configdb_write_database }}"

appsuite_configdb_read_host: "{{ appsuite_configdb_host }}"
appsuite_configdb_read_port: "{{ appsuite_configdb_port }}"
appsuite_configdb_read_database: "{{ appsuite_configdb_database }}"
appsuite_configdb_read_user: "{{ appsuite_configdb_user }}"
appsuite_configdb_read_pass: "{{ appsuite_configdb_pass }}"
appsuite_configdb_read_driver: "com.mysql.jdbc.Driver"
appsuite_configdb_read_url: "jdbc:mysql://{{ appsuite_configdb_read_host }}:{{ appsuite_configdb_read_port }}/{{ appsuite_configdb_read_database }}"

appsuite_userdb_write_alias: "{{ appsuite_configdb_write_host }}"
appsuite_userdb_write_host: "{{ appsuite_configdb_write_host }}"
appsuite_userdb_write_port: "{{ appsuite_configdb_write_port }}"
appsuite_userdb_write_database: "{{ appsuite_configdb_write_database }}"
appsuite_userdb_write_user: "{{ appsuite_configdb_write_user }}"
appsuite_userdb_write_pass: "{{ appsuite_configdb_write_pass }}"
appsuite_userdb_write_driver: "{{ appsuite_configdb_write_driver }}"

appsuite_userdb_read_alias: "{{ appsuite_configdb_write_alias }}_slave"
appsuite_userdb_read_host: "{{ appsuite_configdb_read_host }}"
appsuite_userdb_read_port: "{{ appsuite_configdb_read_port }}"
appsuite_userdb_read_database: "{{ appsuite_configdb_read_database }}"
appsuite_userdb_read_user: "{{ appsuite_configdb_read_user }}"
appsuite_userdb_read_pass: "{{ appsuite_configdb_read_pass }}"
appsuite_userdb_read_driver: "{{ appsuite_configdb_read_driver }}"


appsuite_global_imapserver: "imap://{{ ansible_facts.hostname }}:143"
appsuite_global_smtpserver: "smtp://{{ ansible_facts.hostname }}:25"
appsuite_mail_login_source: login
appsuite_mail_server_source: user
appsuite_transport_server_source: user

# By default, dedicate half of the available memory to JVM, but no more than 8G
appsuite_jvm_memory: "{{ [8192, (ansible_facts.memory_mb.real.total /2)] | min }}"
appsuite_clt_memory: 50  # command line tools

appsuite_tmpdir_path: /var/spool/open-xchange/uploads

appsuite_jkroute: APP1
appsuite_cluster_name: "{{ ansible_facts.hostname }}"
appsuite_object_link_hostname: "{{ ansible_facts.hostname }}"
appsuite_object_link: "http://{{ ansible_facts.hostname }}"
appsuite_extras_link: "http://{{ ansible_facts.hostname }}"
appsuite_network_listener_host: localhost
appsuite_ajp_bind_port: "*"

appsuite_session_max: 0
appsuite_session_max_peruser: 100
appsuite_session_lifetime: 3600000

appsuite_license_key: null
appsuite_master_user: oxadminmaster


appsuite_filestore_path: file:///var/opt/filestore


appsuite_max_upload_size: 104857600
appsuite_max_body_size: 104857600
appsuite_image_transform_maxsize: 10485760
appsuite_image_transform_maxres: 26824090
appsuite_ratelimit_lenient_remote_addresses: []
appsuite_known_proxies: []
appsuite_noipcheck:
  - "127.0.0.1-127.255.255.255"
  - "::1-0:0:0:0:0:0:7fff:ffff"

appsuite_hazelcast_network_join: empty
appsuite_hazelcast_network_static_nodes: []
appsuite_hazelcast_network_interfaces: [127.0.0.1]


appsuite_mail_authtype: ""
appsuite_transport_authtype: ""
appsuite_mailfilter_server_source: user
appsuite_mailfilter_credential_source: session
appsuite_mailfilter_authtype: ""
appsuite_mailfilter_redirect_whitelist: []
appsuite_mailfilter_host: localhost
appsuite_mailfilter_port: 4190

appsuite_mailpush_allowed_clients: >-
  "USM-EAS*", "open-xchange-mobile-api-facade*", "open-xchange-appsuite"

appsuite_messaging_rss_enabled: false
appsuite_messaging_rss_feed_size: 4194304  # 4MB
appsuite_messaging_rss_feed_blacklist: ["127.0.0.1-127.255.255.255", "localhost"]
appsuite_messaging_rss_feed_whitelist_ports: [80, 443]
appsuite_messaging_rss_feed_schemes: ["http", "https", "ftp"]

appsuite_portal_config: ""

appsuite_calendar_ical_refresh_interval: 10080

appsuite_default_permissions: []

appsuite_ldap_url: ldap://localhost:389/dc=example,dc=com
appsuite_ldap_authentication_type: simple
appsuite_ldap_connect_timeout: 10000
appsuite_ldap_read_timeout: 10000
appsuite_ldap_use_full_login_info: false
appsuite_ldap_uid_attr: uid
appsuite_ldap_basedn: ou=Users,ou=OxObjects,dc=open-xchange,dc=com
appsuite_ldap_return_field: ""
appsuite_ldap_ads_bind: false
appsuite_ldap_bindonly: true
appsuite_ldap_scope: subtree
appsuite_ldap_search_filter: "(objectclass=posixAccount)"
appsuite_ldap_bind_dn: ""
appsuite_ldap_bind_password: ""
appsuite_ldap_referral: follow


appsuite_oidc_additional_config: ""
appsuite_oidc_enabled: false
appsuite_oidc_response_type: code
appsuite_oidc_password_grant: false
appsuite_oidc_password_grant_namepart: full
appsuite_oidc_context_lookup_namepart: full
appsuite_oidc_user_lookup_namepart: full
appsuite_oidc_user_lookup_claim: preferred_username
