---

appsuite_version: "7.10.6"
appsuite_repository_release: "Debian{{ ansible_facts.distribution_release[0] | upper }}{{ ansible_facts.distribution_release[1:] }}"

# The Mobile API Facade versioning differs from that of App Suite
mobileapifacade_repository_versionmap:
  "7.10.5": "1.12.2"
  "7.10.6": "1.14.3"
mobileapifacade_version: {{ moileapifacade_repository_versionmap[appsuite_version] }}

mobileapifacade_repository_facade: >-
  deb https://software.open-xchange.com/products/mobile-api-facade/{{ mobileapifacade_version }}/mobile-api-facade/{{ appsuite_repository_release }}/ /

mobileapifacade_apache_backends:
  - "http://localhost:8007"
