---

- name: Install OX AppSuite
  ansible.builtin.import_tasks: install.yml
  tags:
    - "role::appsuite"
    - "role::appsuite:install"

- name: Initialize OX AppSuite
  ansible.builtin.import_tasks: init.yml
  tags:
    - "never"
    - "role::appsuite:init"

- name: Setup OX AppSuite Middleware node with oxinstaller
  ansible.builtin.import_tasks: oxinstaller.yml
  tags:
    - "never"
    - "role::appsuite:oxinstaller"

- name: Configure OX AppSuite
  ansible.builtin.import_tasks: config.yml
  tags:
    - "role::appsuite"
    - "role::appsuite:config"

- name: Configure LDAP authplugin
  ansible.builtin.import_tasks: ldap.yml
  when: "appsuite_authplugin == 'open-xchange-authentication-ldap'"
  tags:
    - "role::appsuite"
    - "role::appsuite:ldap"

- name: Configure OpenID Connect client
  ansible.builtin.import_tasks: oidc.yml
  when: "appsuite_oidc_enabled"
  tags:
    - "role::appsuite"
    - "role::appsuite:oidc"
