---

- name: Install open-xchange-oidc
  ansible.builtin.apt:
    name: open-xchange-oidc
  notify: "Restart Open-Xchange"

- name: Render openid.properties
  ansible.builtin.template:
    src: opt/open-xchange/etc/openid.properties.j2
    dest: /opt/open-xchange/etc/openid.properties
    owner: root
    group: root
    mode: "0644"
  notify: "Restart Open-Xchange"
