---

- name: Run the App Suite installer
  ansible.builtin.command: >-
    /opt/open-xchange/sbin/oxinstaller
    --servername {{ appsuite_servername }}
    --configdb-readhost {{ appsuite_configdb_read_host }}
    --configdb-readport {{ appsuite_configdb_read_port }}
    --configdb-writehost {{ appsuite_configdb_write_host }}
    --configdb-writeport {{ appsuite_configdb_write_port }}
    --configdb-user {{ appsuite_configdb_write_user }}
    --configdb-pass {{ appsuite_configdb_write_pass }}
    --imapserver {{ appsuite_global_imapserver }}
    --smtpserver {{ appsuite_global_smtpserver }}
    --mail-login-src {{ appsuite_mail_login_source }}
    --mail-server-src {{ appsuite_mail_server_source }}
    --transport-server-src {{ appsuite_transport_server_source }}
    --servermemory {{ appsuite_jvm_memory }}
    --clt-memory {{ appsuite_clt_memory }}
    --tmpdir-path {{ appsuite_tmpdir_path }}
    --jkroute {{ appsuite_jkroute }}
    --object-link-hostname {{ appsuite_object_link_hostname }}
    --extras-link {{ appsuite_extras_link }}
    --maxSession {{ appsuite_session_max }}
    --sessionDefLifeTime {{ appsuite_session_lifetime }}
    --name-of-oxcluster {{ appsuite_cluster_name }}
    --network-listener-host {{ appsuite_network_listener_host }}
    --ajp-bind-port {{ appsuite_ajp_bind_port }}
    {% if appsuite_license_key is none %}
    --no-license
    {% else %}
    --add-license {{ appsuite_license_key }}
    {% endif %}
    --master-user {{ appsuite_master_user }}
    --master-pass {{ appsuite_master_pass }}
  changed_when: true
